#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HelloFacebookSample.Resource", IsApplication=true)]

namespace HelloFacebookSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_blue = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_text_color = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_picker_search_bar_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_picker_search_bar_text = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_loginview_compound_drawable_padding = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_loginview_padding_bottom = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_loginview_padding_left = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_loginview_padding_right = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_padding_top = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_loginview_text_size = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_picker_divider_width = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_picker_place_image_size = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_profilepictureview_preset_size_large = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_profilepictureview_preset_size_normal = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_profilepictureview_preset_size_small = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_tooltip_horizontal_padding = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_blue_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_blue_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_blue_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_check_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_check_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_grey_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_grey_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_grey_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_close = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_inverse_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_list_divider = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_list_section_header_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_loginbutton_silver = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_logo = 2130837519;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_picker_default_separator_color = 2130837545;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_picker_item_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_picker_list_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_picker_list_longpressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_picker_list_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_picker_list_selector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_picker_list_selector_background_transition = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_picker_list_selector_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_picker_magnifier = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_picker_top_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_place_default_icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_profile_default_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_profile_picture_blank_portrait = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_profile_picture_blank_square = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_tooltip_black_background = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_tooltip_black_bottomnub = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_tooltip_black_topnub = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_tooltip_black_xout = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_tooltip_blue_background = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_tooltip_blue_bottomnub = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_tooltip_blue_topnub = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_tooltip_blue_xout = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_top_background = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_top_button = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040015
			public const int com_facebook_body_frame = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int com_facebook_button_xout = 2130968599;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_login_activity_progress_bar = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_picker_activity_circle = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_picker_checkbox = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_picker_checkbox_stub = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_picker_divider = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_picker_done_button = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_picker_image = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_picker_list_section_header = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_picker_list_view = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_picker_profile_pic_stub = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_picker_row_activity_circle = 2130968582;
			
			// aapt resource value: 0x7f040014
			public const int com_facebook_picker_search_text = 2130968596;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_picker_title = 2130968586;
			
			// aapt resource value: 0x7f040011
			public const int com_facebook_picker_title_bar = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int com_facebook_picker_title_bar_stub = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_picker_top_bar = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int com_facebook_search_bar_view = 2130968595;
			
			// aapt resource value: 0x7f040019
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int com_facebook_tooltip_bubble_view_text_body = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int com_facebook_usersettingsfragment_login_button = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int com_facebook_usersettingsfragment_logo_image = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int com_facebook_usersettingsfragment_profile_name = 2130968603;
			
			// aapt resource value: 0x7f040025
			public const int fragment_container = 2130968613;
			
			// aapt resource value: 0x7f04001f
			public const int greeting = 2130968607;
			
			// aapt resource value: 0x7f040002
			public const int large = 2130968578;
			
			// aapt resource value: 0x7f04001e
			public const int login_button = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int main_ui_container = 2130968605;
			
			// aapt resource value: 0x7f040001
			public const int normal = 2130968577;
			
			// aapt resource value: 0x7f040023
			public const int pickFriendsButton = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int pickPlaceButton = 2130968612;
			
			// aapt resource value: 0x7f040012
			public const int picker_subtitle = 2130968594;
			
			// aapt resource value: 0x7f040022
			public const int postPhotoButton = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int postStatusUpdateButton = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int profilePicture = 2130968608;
			
			// aapt resource value: 0x7f040000
			public const int small = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_friendpickerfragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_activity_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_picker_activity_circle_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_checkbox = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_image = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_list_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_section_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_search_box = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_title_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar_stub = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_placepickerfragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment_list_row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_search_bar_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_tooltip_bubble = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_usersettingsfragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int main = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070028
			public const int app_id = 2131165224;
			
			// aapt resource value: 0x7f07001a
			public const int app_name = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int cancelled = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_choose_friends = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_dialogloginactivity_ok_button = 2131165184;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_internet_permission_error_message = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_internet_permission_error_title = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_loading = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_loginview_cancel_action = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_loginview_log_in_button = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_loginview_log_out_action = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_loginview_log_out_button = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_loginview_logged_in_as = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_logged_in_using_facebook = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_logo_content_description = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_nearby = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_picker_done_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_placepicker_subtitle_format = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_requesterror_password_changed = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_requesterror_permissions = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_requesterror_reconnect = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_requesterror_relogin = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_requesterror_web_login = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int com_facebook_tooltip_default = 2131165209;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_usersettingsfragment_log_in_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_usersettingsfragment_logged_in = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int error = 2131165217;
			
			// aapt resource value: 0x7f070029
			public const int exception = 2131165225;
			
			// aapt resource value: 0x7f07001e
			public const int hello_user = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int no_friends_selected = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int no_place_selected = 2131165222;
			
			// aapt resource value: 0x7f07001d
			public const int ok = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int permission_not_granted = 2131165212;
			
			// aapt resource value: 0x7f070023
			public const int photo_post = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int pick_seattle_place = 2131165223;
			
			// aapt resource value: 0x7f070022
			public const int status_update = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int success = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int successfully_posted_post = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int you_picked = 2131165220;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_loginview_default_style = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_loginview_silver_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tooltip_bubble_text = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_friend_picker_fragment = new int[]
			{
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[]
			{
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
